package com.gien.gits.ontology;

/**
 * 人工门禁类型 — 对应15种Human Gate
 */
public enum GateType {
    A01_OUTREACH,
    A02_SIGNAL_CONFIRM,
    A03_OPPORTUNITY_VALIDATE,
    B01_CONTEXT_ENRICH,
    B02_FACT_VALIDATE,
    C01_PREVISIT_APPROVE,
    C02_REPORT_APPROVE,
    D01_PRODUCT_RECOMMEND,
    E01_EXIT_CONFIRM,
    F01_CRM_WRITEBACK,
    F02_CREDIT_CHECK,
    F03_PRICE_APPROVE,
    F04_RISK_REVIEW,
    F05_RECORDING_APPROVE,
    F06_CONTROLLED_ACTION
}
